[platformio]
default_envs = atoms3r_cam_sender, atoms3_cam_receiver, m5fire_cam_receiver


[env:atoms3r_cam_sender]
platform = espressif32
board = m5stack-atoms3
framework = arduino
monitor_speed = 115200
lib_deps =
    m5stack/M5Unified@^0.1.12
    hpsaturn/ESPNowCam@^0.1.12
build_src_filter = +<espnow_cam_sender.cpp>

# === Enable PSRAM === #
board_build.arduino.memory_type = dio_opi
board_upload.flash_size = 8MB
build_flags = -DBOARD_HAS_PSRAM


[env:atoms3_cam_receiver]
platform = espressif32
board = m5stack-atoms3
framework = arduino
monitor_speed = 115200
lib_deps =
    m5stack/M5Unified@^0.1.12
    hpsaturn/ESPNowCam@^0.1.12
build_src_filter = +<espnow_cam_receiver.cpp>

[env:m5fire_cam_receiver]
platform = espressif32
board = m5stack-fire
framework = arduino
monitor_speed = 115200
lib_deps =
    m5stack/M5Unified@^0.1.12
    hpsaturn/ESPNowCam@^0.1.12
build_src_filter = +<espnow_cam_receiver.cpp>
